# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 17:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raiz', models.BooleanField(default=True, verbose_name='É raiz ?')),
                ('tipo', models.CharField(default='PAI', max_length=10, validators=[django.core.validators.RegexValidator('PAI|FILHO', 'Tipo inválido', code='Inconsistência')])),
                ('conteudo', models.TextField(validators=[django.core.validators.RegexValidator('^\\s*$', 'Conteúdo inválido', code='Inconsistência')], verbose_name='Conteúdo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('comentario_pai', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='timeline.Comentario')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meus_comentarios', to='accounts.Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postagens', to='accounts.Perfil')),
            ],
        ),
        migrations.AddField(
            model_name='comentario',
            name='postagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='timeline.Postagem'),
        ),
    ]
