# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 13:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='tipo',
            field=models.CharField(choices=[('PAI', 'Comentário Raiz'), ('FILHO', 'Comentário Resposta')], default='PAI', max_length=10, validators=[django.core.validators.RegexValidator('PAI|FILHO', 'Tipo inválido', code='Inconsistência')]),
        ),
    ]
