# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-29 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0002_turma_disciplina'),
        ('timeline', '0002_auto_20161013_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('postagem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timeline.Postagem')),
                ('mensagem', models.TextField()),
            ],
            bases=('timeline.postagem',),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('postagem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timeline.Postagem')),
                ('descricao', models.CharField(max_length=30)),
                ('horario', models.DateTimeField()),
            ],
            bases=('timeline.postagem',),
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('postagem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timeline.Postagem')),
                ('descricao', models.TextField()),
                ('data_entrega', models.DateTimeField()),
            ],
            bases=('timeline.postagem',),
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=30)),
                ('rua', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_resposta', models.URLField()),
                ('status', models.CharField(choices=[(True, 'Concluído'), (False, 'Não Concluído')], default=False, max_length=5)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='accounts.Inscricao')),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='timeline.Exercicio')),
            ],
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='postagem',
        ),
        migrations.AddField(
            model_name='postagem',
            name='conteudo_relacionado',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postagem',
            name='objeto',
            field=models.PositiveIntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postagem',
            name='postado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postagem',
            name='turma',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='postagens', to='accounts.Turma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento', to='timeline.Localizacao'),
        ),
    ]
