# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20161102_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='nome',
            field=models.CharField(default='', max_length=100, verbose_name='Descrição da Turma'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='codigo_ativo',
            field=models.BooleanField(default=True),
        ),
    ]
